"""
boneseg3d/product/operationalize.py
=====================================
PHASE 3 — OPERATIONALIZE
Role:  Data Engineer
Goal:  Register monitoring hooks, SLA thresholds, and health-check probes
       so the pipeline is observable from the moment it goes live.

This module does NOT run the ML steps — those live in boneseg3d/agents/.
It focuses on:
  • Inference latency SLA registration
  • GPU utilisation logging hooks
  • Data drift probe (feature-space shift between training and new CTs)
  • Dead-man's-switch alerting (pipeline stall detection)
  • Model registry entry creation

Outputs
───────
  outputs/product/monitoring_config.json
  logs/sla_thresholds.json
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from boneseg3d.utils.logging_utils import get_logger

log = get_logger("operationalize")

OUTPUT_DIR   = Path("outputs/product")
LOGS_DIR     = Path("logs")


# ── SLA definitions ───────────────────────────────────────────────────────────

@dataclass
class InferenceSLA:
    """Latency and quality thresholds that trigger alerts in production."""
    max_inference_time_per_volume_sec: float  = 120.0   # H100, sliding window
    min_dice_vs_baseline: float               = 0.65    # alert if model regresses
    max_false_positive_rate_per_scan: float   = 3.0     # FP lesions / scan
    max_gpu_memory_gb: float                  = 40.0    # H100 = 80 GB; budget 40 GB


@dataclass
class DataDriftProbe:
    """
    Lightweight KL-divergence check on Hounsfield Unit (HU) histograms
    to catch scanner drift or protocol changes.
    """
    reference_histogram_path: str  = "outputs/product/hu_histogram_reference.npy"
    kl_divergence_alert_threshold: float = 0.15
    n_bins: int = 256
    hu_range: tuple[int, int] = (-1000, 2000)


@dataclass
class ModelRegistryEntry:
    model_id: str
    version: str
    backbone: str           # "nnunet" | "swinunetr" | "ensemble"
    training_dataset: str
    val_dice: float | None
    registered_at: str
    artifact_path: str
    status: str             # "staging" | "production" | "deprecated"


# ── Monitoring hooks ──────────────────────────────────────────────────────────

def _register_inference_latency_hook(sla: InferenceSLA, cfg: Any) -> None:
    """
    Write SLA thresholds to logs/ so the inference wrapper can read them
    and raise warnings / log structured events without importing this module.
    """
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    sla_path = LOGS_DIR / "sla_thresholds.json"
    sla_path.write_text(json.dumps(asdict(sla), indent=2), encoding="utf-8")
    log.info(f"[MONITOR] SLA thresholds registered → {sla_path}")


def _register_gpu_utilisation_hook(cfg: Any) -> None:
    """
    Write a gpu_monitor.sh wrapper script that samples nvidia-smi every 30 s
    and appends to logs/gpu_utilisation.csv during training runs.
    """
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    script = (
        "#!/bin/bash\n"
        "# Auto-generated by boneseg3d/product/operationalize.py\n"
        "echo 'timestamp,gpu_id,util_pct,mem_used_mb,temp_c' >> logs/gpu_utilisation.csv\n"
        "while true; do\n"
        "  nvidia-smi --query-gpu=timestamp,index,utilization.gpu,"
        "memory.used,temperature.gpu "
        "--format=csv,noheader,nounits >> logs/gpu_utilisation.csv\n"
        "  sleep 30\n"
        "done\n"
    )
    script_path = Path("scripts/gpu_monitor.sh")
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(script, encoding="utf-8")
    script_path.chmod(0o755)
    log.info(f"[MONITOR] GPU utilisation hook → {script_path}")


def _register_data_drift_probe(probe: DataDriftProbe, cfg: Any) -> None:
    """Persist the drift probe config so the inference pipeline can run it live."""
    probe_path = OUTPUT_DIR / "data_drift_probe.json"
    probe_path.write_text(json.dumps(asdict(probe), indent=2), encoding="utf-8")
    log.info(f"[MONITOR] Data drift probe config → {probe_path}")


def _register_model_entry(cfg: Any) -> ModelRegistryEntry:
    """Create an initial staging entry in the model registry."""
    entry = ModelRegistryEntry(
        model_id="boneseg3d-v0",
        version=getattr(cfg, "version", "0.1.0"),
        backbone="ensemble",
        training_dataset="TCIA-MM-CT",
        val_dice=None,   # populated by benchmark_segmentation_performance()
        registered_at=datetime.now(timezone.utc).isoformat(),
        artifact_path="outputs/models/boneseg3d_ensemble.pt",
        status="staging",
    )
    registry_path = OUTPUT_DIR / "model_registry.json"

    # Load existing registry or start fresh
    if registry_path.exists():
        registry = json.loads(registry_path.read_text())
    else:
        registry = {"entries": []}

    registry["entries"].append(asdict(entry))
    registry_path.write_text(json.dumps(registry, indent=2), encoding="utf-8")
    log.info(f"[MONITOR] Model registry entry created → {registry_path}")
    return entry


def _write_monitoring_config(
    sla: InferenceSLA,
    probe: DataDriftProbe,
    model_entry: ModelRegistryEntry,
    cfg: Any,
) -> None:
    config = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "sla": asdict(sla),
        "data_drift_probe": asdict(probe),
        "model_registry_entry": asdict(model_entry),
        "alert_channels": getattr(cfg.monitoring, "alert_channels", ["log"]),
        "heartbeat_interval_sec": getattr(cfg.monitoring, "heartbeat_interval_sec", 300),
    }
    mc_path = OUTPUT_DIR / "monitoring_config.json"
    mc_path.write_text(json.dumps(config, indent=2), encoding="utf-8")
    log.info(f"[MONITOR] Monitoring config → {mc_path}")


# ── Entry point ───────────────────────────────────────────────────────────────

def register_monitoring_hooks(cfg: Any) -> None:
    """
    Register all monitoring, SLA, and model registry hooks.

    Called by: main.py → operationalize() (after ML tasks complete)
    Role:      Data Engineer
    """
    log.info("Registering monitoring hooks and model registry entry...")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    sla   = InferenceSLA()
    probe = DataDriftProbe()

    _register_inference_latency_hook(sla, cfg)
    _register_gpu_utilisation_hook(cfg)
    _register_data_drift_probe(probe, cfg)
    model_entry = _register_model_entry(cfg)
    _write_monitoring_config(sla, probe, model_entry, cfg)

    log.info("✓ All monitoring hooks registered.")